### ISSUE TITLE
Moon and Star Bug

### ISSUE THREAD

**Issue by birdiesgrimm** [Guitarninja2/septimus#476] opened 2022-05-01 01:10 UTC
The stuffed dog in Little Vivec by the Darossa house is invisible. It is supposed to be to the left of the log pile, however, the hit box is somewhere in the front of the log pile.

**Comment by Guitarninja2** [comment] 2022-05-02 15:54
duplicate of this report: https://github.com/Guitarninja2/septimus/issues/463

**Closed by Guitarninja2** 2022-05-02 15:54 UTC
