### ISSUE TITLE
Hair clipping through hoods.

### ISSUE THREAD

**Issue by adam-ciszewski** [Guitarninja2/septimus#108] opened 2021-12-15 17:59 UTC
### Subject of the issue
Hair is clipping through hoods after the update from 1.10 beta to 1.10.

### Your environment
Modlist version 1.10
Custom mods outside of modlist:
- NightEyeENB fix
- Simply Faster Arrows and Bolts
- Know Your Enemy- Trait-based resistances and weaknesses.
- Experiance

### Steps to reproduce
Put on a mage hood. Tested with Vigilants light hoods, and novice mage hood.

### Expected behaviour
Hair is hidden under the hood.

### Actual behaviour
Hair clipping through the hood.
![enb2021_12_15_17_51_11](https://user-images.githubusercontent.com/40968511/146240254-c096043e-a868-45dc-ae4a-4864031b0184.jpg)

**Comment by Calcyon85** [comment] 2021-12-25 06:25
Tried with multiple different hoods and hairstyles and couldn't reproduce

**Comment by Guitarninja2** [comment] 2021-12-25 06:34
Likely fixed in 2.0

**Closed by Guitarninja2** 2021-12-25 06:34 UTC
